### ISSUE TITLE
Add @BindsInstance example

### ISSUE THREAD

**Issue by nejtr0n** [ravn/dagger2-hello-world#1]
Hi. 
It would be greate, if you add @BindsInstance usage example too for newbies like me =)
https://google.github.io/dagger/api/latest/dagger/BindsInstance.html
Especially with annotated types.

**Comment by ravn** [comment]
This is not a tutorial, just the tiniest example I could figure out.  I have never used BindsInstance.  What would it be good for?

**Comment by nejtr0n** [comment]
Its useful for binding data at the time of building the component. (For example cmd args).
```
 App app = DaggerAppComponent
      .builder()
      .userName(args[0])
      .build()
      .app();
```
But I were unable to write annotadet type for username.
I had to use guice instead of dagger (It's much easier to do it in guice).

**Comment by ravn** [comment]
Ah, we do that with our configuration map which needs to be provided at runtime.  All you need to do is have a @Provider require your userName (which you annotate appropriately) but not have a provider for the userName (@Named("userName)).  Then dagger should construct and require the userName method.
