### ISSUE TITLE
Using create()

### ISSUE THREAD

**Issue by arjunpola** [ravn/dagger2-hello-world#2]
Not super important but any thoughts to replace?

`HelloWorldComponent daggerGeneratedComponent = DaggerMain_HelloWorldComponent.builder().build();`

to

`  HelloWorldComponent daggerGeneratedComponent = DaggerMain_HelloWorldComponent.create();`

**Comment by ravn** [comment]
I use Dagger in a setting where we must provide a configuration map at runtime to complete the Dagger configuration.  (Think that dagger look things up in a property file - I may write a blog entry on it). That looks like

    DaggerValidateXMLMain_ValidateXMLComponent.builder().configurationMap(m).build()

In other words a method call between builder() and build().  Therefore I have not had much experience with create(), and even if it is simpler I think it may be too simple.
